name: maestral
base: core18
license: MIT
adopt-info: maestral
icon: maestral/resources/maestral.png
summary: An open-source Dropbox client for macOS and Linux.
description: |
  Maestral is light-weight and simple Dropbox client for Linux and macOS.
  It allows two-way syncing with your Dropbox, setting up a 'mignore' file
  similar to 'gitignore' and syncing multiple Dropbox accounts.

grade: stable
confinement: strict

apps:
  maestral:
    command: maestral
    extensions:
      - kde-neon
    plugs:
      - home
      - network
      - unity7
      - opengl
  maestral-qt:
    command: maestral gui
    desktop: share/applications/maestral.desktop
    extensions:
      - kde-neon
    plugs:
      - home
      - network
      - unity7
      - opengl

environment:
  # Coerce XDG_CURRENT_DESKTOP to Unity so that App Indicators
  # are used and do not fall back to Notification Area applets
  # or disappear completely.
  XDG_CURRENT_DESKTOP: Unity:Unity7

parts:
  maestral:
    source: .
    plugin: python
    python-version: python3
    stage-packages:
      # Use the version from the repo to avoid the xcb not found error
      - python3-pyqt5
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(grep version maestral/__init__.py | cut -d'"' -f2)

  maestral-qt:
    source: https://github.com/SamSchott/maestral-qt.git
    plugin: python
    python-version: python3
    override-build: |
      sed -i "s|'PyQt5.*||g" setup.py
      sed -i "s|'maestral==.*||g" setup.py
      snapcraftctl build
    override-prime: |
      snapcraftctl prime
      sed -i 's|Icon = maestral|Icon=${SNAP}/share/icons/hicolor/512x512/apps/maestral.png|g' share/applications/maestral.desktop
  cleanup:
    after: [maestral, maestral-qt]
    plugin: nil
    build-snaps: [ kde-frameworks-5-core18 ]
    override-prime: |
        set -eux
        cd /snap/kde-frameworks-5-core18/current
        find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/{} \;
