name: build

on:
  push:
    tags:
      - 'v*.*.*'

  workflow_dispatch:

  schedule:
    - cron: "19 3 * * *" # everyday at 03:19

jobs:
  build_macos:
    runs-on: macos-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.merged.sha }}

      - name: Fetching tags
        run: git fetch --prune --unshallow --tags

      - name: Prepare
        id: prep
        run: |
          BUILD_VERSION=noop

          if [ "${{ github.event_name }}" = "schedule" ]; then
            BUILD_VERSION=nightly-$(date -u +'%Y-%m-%d-%H%M')-$GIT_BRANCH
          elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            BUILD_VERSION=manual-$(date -u +'%Y-%m-%d-%H%M')-$GIT_BRANCH
          elif [[ $GITHUB_REF == refs/tags/* ]]; then
            BUILD_VERSION=""
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            BUILD_VERSION=pr-${{ github.event.number }}
          fi

          echo ::set-output name=version::${BUILD_VERSION}

      - name: Import signing certificate into keychain
        run: |
          KEYCHAIN_FILE=default.keychain
          KEYCHAIN_PASSWORD=myvoiceismypassport
          security create-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_FILE
          security default-keychain -s $KEYCHAIN_FILE
          security unlock-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_FILE
          security import <(echo $SIGNING_CERTIFICATE_P12_DATA | base64 --decode) \
                          -f pkcs12 \
                          -k $KEYCHAIN_FILE \
                          -P $SIGNING_CERTIFICATE_PASSWORD \
                          -T /usr/bin/codesign \
                          -T /usr/bin/security
          security set-key-partition-list -S apple-tool:,apple: -s -k $KEYCHAIN_PASSWORD $KEYCHAIN_FILE
          security find-identity -v
        env:
          SIGNING_CERTIFICATE_P12_DATA: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA }}
          SIGNING_CERTIFICATE_PASSWORD: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}

      - name: Install dependencies that require building
        # We build all extension modules (PyInstaller bootloader, watchdog, etc) and Python
        # itself from source with the latest SDK and a deployment target of macOS 10.13.
        run: |
          # reinstall Python
          brew uninstall --ignore-dependencies python3
          export HOMEBREW_MACOSX_DEPLOYMENT_TARGET=$MACOSX_DEPLOYMENT_TARGET
          brew tap samschott/python
          brew install -s samschott/python/python@3.8
          python3 -c "import sys; print(sys.version)"

          # reinstall gettext
          curl -L "https://bintray.com/homebrew/bottles/download_file?file_path=gettext-0.21.high_sierra.bottle.tar.gz" -o "gettext-0.21.high_sierra.bottle.tar.gz"
          brew reinstall -f "gettext-0.21.high_sierra.bottle.tar.gz"

          # reinstall openssl
          curl -L "https://bintray.com/homebrew/bottles/download_file?file_path=openssl%401.1-1.1.1h.high_sierra.bottle.tar.gz" -o "openssl%401.1-1.1.1h.high_sierra.bottle.tar.gz"
          brew uninstall --ignore-dependencies openssl
          brew install -f "openssl%401.1-1.1.1h.high_sierra.bottle.tar.gz"

          # reinstall sqlite
          curl -L "https://bintray.com/homebrew/bottles/download_file?file_path=sqlite-3.33.0.high_sierra.bottle.tar.gz" -o "sqlite-3.33.0.high_sierra.bottle.tar.gz"
          brew reinstall -f "sqlite-3.33.0.high_sierra.bottle.tar.gz"

          # build and install PyInstaller
          git clone https://github.com/pyinstaller/pyinstaller.git package/build/pyinstaller
          cd package/build/pyinstaller
          git apply ../../patch/pyinstaller_macos_11.patch
          cd bootloader
          python3 ./waf all
          cd "$GITHUB_WORKSPACE"
          python3 -m pip install --upgrade package/build/pyinstaller

          # build and install watchdog
          python3 -m pip install --upgrade watchdog
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.13
          CFLAGS: -mmacosx-version-min=10.13
          CPPFLAGS: -mmacosx-version-min=10.13
          LDFLAGS: -mmacosx-version-min=10.13
          LINKFLAGS: -mmacosx-version-min=10.13

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade dmgbuild
          if [ "${{ github.event_name }}" = "tags" ]; then
            # fetch gui dependency on tagged release
            python3 -m pip install .[gui]
          else
            # checkout latest gui from github
            python3 -m pip install .
            python3 -m pip install git+https://github.com/samschott/maestral-cocoa
          fi

      - name: Build app
        shell: bash --noprofile --norc -eo pipefail {0}
        run: |
          cd package
          python3 -OO -m PyInstaller -y --clean -w maestral_macos.spec
          cp bin/maestral_cli dist/Maestral.app/Contents/MacOS/maestral_cli
          cd "$GITHUB_WORKSPACE"
          xattr -cr package/dist/Maestral.app
          codesign --sign "Developer ID Application: Sam Schott" \
                   --entitlements package/entitlements.plist \
                   --options runtime \
                   --force --deep package/dist/Maestral.app
          codesign --verify --deep package/dist/Maestral.app
        env:
          BUNDLE_VERSION: ${{ github.run_number }}

      - name: Create dmg
        id: dmg
        run: |
          MAESTRAL_VERSION=$( maestral -V )
          DMG_NAME="Maestral-${{ steps.prep.outputs.version }}-$MAESTRAL_VERSION.dmg"
          DMG_NAME=${DMG_NAME//--/-}
          cd package/dist
          dmgbuild -s ../dmg_settings.py Maestral $DMG_NAME
          codesign --sign "Developer ID Application: Sam Schott" $DMG_NAME
          codesign --verify $DMG_NAME
          cd "$GITHUB_WORKSPACE"

          echo ::set-output name=dmg_name::${DMG_NAME}

      - name: Notarize app
        run: |
          npx notarize-cli --bundle-id "com.samschott.maestral" \
                           --file "package/dist/${{ steps.dmg.outputs.dmg_name }}"
        env:
          NOTARIZE_USERNAME: ${{ secrets.NOTARIZE_USERNAME }}
          NOTARIZE_PASSWORD: ${{ secrets.NOTARIZE_PASSWORD }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dmg
          path: "package/dist/${{ steps.dmg.outputs.dmg_name }}"
