name: Lint with flake8 and mypy

on: [pull_request]

jobs:
  flake:
    name: Lint with flake8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
        pip install .
    - name: Lint with flake8
      run: |
        flake8 . --count --ignore=C901,W503 --max-line-length=130 --statistics

  mypy:
    name: Type checking with mypy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install mypy
        pip install .
    - name: Type checking with mypy
      run: |
        mypy --warn-unused-ignores maestral
