name: Run tests

on:
  pull_request_target:
    paths:
      # run tests only when the python code has changed
      - 'maestral/**.py'
      - 'tests/**.py'

  workflow_dispatch:

jobs:
  tests:
    name: Run tests
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest]
        python-version: [3.6, ]
        include:
          # use two different Dropbox accounts to run tests in parallel
          - platform: ubuntu-latest
            token: DROPBOX_REFRESH_TOKEN_1

          - platform: macos-latest
            token: DROPBOX_REFRESH_TOKEN_2

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.merged.sha }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pytest
          python -m pip install --upgrade pytest-cov
          python -m pip install .

      - name: Get short-lived Dropbox token
        # We generate a short-lived auth token which is passed to the test runner as
        # an environment variable. At no point does the test code, potentially from a
        # malicious PR, get access to a long lived token.
        run: |
          auth_result=$(curl https://api.dropbox.com/oauth2/token \
              -d grant_type=refresh_token \
              -d refresh_token=${{ secrets[matrix.token] }} \
              -d client_id=2jmbq42w7vof78h)
          token=$(echo $auth_result | python -c "import sys, json; print(json.load(sys.stdin)['access_token'])")
          echo "::add-mask::$token"
          echo "DROPBOX_TOKEN=$token" >> $GITHUB_ENV

      - name: Test with pytest
        run: |
          pytest --cov=maestral --cov-report=xml .

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: pytest
          env_vars: OS,PYTHON
          name: pytests
        env:
          OS: ${{ matrix.platform }}
          PYTHON: ${{ matrix.python-version }}
